### ISSUE TITLE
Cryptic exception when region is not set

### ISSUE THREAD

**Issue by darrenhaken** [k1LoW/awspec#325]
I was trying to run awspec tests on Jenkins where the AWS region was not set. The error I receive is the following:

```
Failures:

  1) alb 'app_load_balancer' should be active
     Failure/Error: it { is_expected.to be_active }
     
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./.bundle/ruby/2.1.0/gems/awspec-0.85.2/lib/awspec/type/alb.rb:17:in `block (2 levels) in <class:Alb>'
     # ./spec/application_load_balancer_spec.rb:4:in `block (2 levels) in <top (required)>'
```

This caused us to lose a *lot* of time where if awspec where a readable error would help a lot.

Does this make sense?
